      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run tests
        working-directory: backend
        run: npm test -- --passWithNoTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .

      - name: Push Docker image
        working-directory: backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      # ——— Despliegue en Cloud Run ———
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Enable Cloud Run API
        run: gcloud services enable run.googleapis.com

      - name: Configure gcloud defaults
        run: |
          gcloud config set run/region us-central1
          gcloud config set run/platform managed

      - name: Deploy to Cloud Run
        working-directory: backend
        run: |
          gcloud run deploy backend-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest \
            --allow-unauthenticated \
            --memory=512Mi \
            --concurrency=80 \
            --quiet